version: '3'

services:
  python-redmine-server:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/src
    depends_on:
      - reverse-proxy
  reverse-proxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
  my-vue-app:
    build: ./frontend
    ports:
      - '8081:8080'
    depends_on:
      - reverse-proxy